### PR TITLE
Dart SDK installer script

### PR DESCRIPTION
**Pull request by Viha27**

### CODE REVIEW

**Comment by agentmilindu** [comment]
Hi @Viha27, Thanks for your contribution. However, we no longer need to manage individual `sh` files as these are generated by the script you have defined in the `toml` file. When I merge this PR, the Continuous Integration pipeline will generate each `sh` and `min.sh` files according to your `toml` file. As you haven't updated the `toml` file with your installer instructions, all your installer `sh` files will be replaced by the Python installation instructions as in [your `toml` file](https://github.com/leopardslab/installer.to/pull/96/files#diff-262f4c5a321f22c2587d794afd40a1ea153cd83ed92a0d7477d622cbea1a1288). 

Refer to [this `toml` file](https://github.com/leopardslab/installer.to/blob/master/installers/docker/installer.toml) and update the `toml` file accordingly; the CI pipeline will take care of the rest!

**Comment by Viha27** [comment]
> Hi @Viha27, Thanks for your contribution. However, we no longer need to manage individual `sh` files as these are generated by the script you have defined in the `toml` file. When I merge this PR, the Continuous Integration pipeline will generate each `sh` and `min.sh` files according to your `toml` file. As you haven't updated the `toml` file with your installer instructions, all your installer `sh` files will be replaced by the Python installation instructions as in [your `toml` file](https://github.com/leopardslab/installer.to/pull/96/files#diff-262f4c5a321f22c2587d794afd40a1ea153cd83ed92a0d7477d622cbea1a1288).
> 
> Refer to [this `toml` file](https://github.com/leopardslab/installer.to/blob/master/installers/docker/installer.toml) and update the `toml` file accordingly; the CI pipeline will take care of the rest!

I edited toml file but still showed same error

**Comment by Viha27** [comment]
> > Hi @Viha27, Thanks for your contribution. However, we no longer need to manage individual `sh` files as these are generated by the script you have defined in the `toml` file. When I merge this PR, the Continuous Integration pipeline will generate each `sh` and `min.sh` files according to your `toml` file. As you haven't updated the `toml` file with your installer instructions, all your installer `sh` files will be replaced by the Python installation instructions as in [your `toml` file](https://github.com/leopardslab/installer.to/pull/96/files#diff-262f4c5a321f22c2587d794afd40a1ea153cd83ed92a0d7477d622cbea1a1288).
> > Refer to [this `toml` file](https://github.com/leopardslab/installer.to/blob/master/installers/docker/installer.toml) and update the `toml` file accordingly; the CI pipeline will take care of the rest!
> 
> I edited toml file but still showed same error

@agentmilindu  How do I run this locally to test my toml file is correctly written ?

**Comment by Viha27** [comment]
> > > Hi @Viha27, Thanks for your contribution. However, we no longer need to manage individual `sh` files as these are generated by the script you have defined in the `toml` file. When I merge this PR, the Continuous Integration pipeline will generate each `sh` and `min.sh` files according to your `toml` file. As you haven't updated the `toml` file with your installer instructions, all your installer `sh` files will be replaced by the Python installation instructions as in [your `toml` file](https://github.com/leopardslab/installer.to/pull/96/files#diff-262f4c5a321f22c2587d794afd40a1ea153cd83ed92a0d7477d622cbea1a1288).
> > > Refer to [this `toml` file](https://github.com/leopardslab/installer.to/blob/master/installers/docker/installer.toml) and update the `toml` file accordingly; the CI pipeline will take care of the rest!
> > 
> > 
> > I edited toml file but still show the same error
> 
> @agentmilindu How do I run this locally to test my toml file is correctly written ?

Wthat are the files should push .?  only toml file or both installer.toml and installer.sh .?

**Review by agentmilindu — APPROVED** [review]

**Comment by agentmilindu** [comment]
@Viha27 Yes, only toml file

**Pull request merged**
